name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^5.2.0
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^1.4.0
  image: ^2.0.7
  intl:
  email_validator: ^1.0.6
  google_fonts: ^1.1.1
  page_transition: ^1.1.7+6
  google_maps_flutter: ^1.1.1
  geolocator: ^6.1.14
  geocoder: ^0.2.1
  geoflutterfire: ^2.2.1
  modal_progress_hud: ^0.1.3
  flutter_credit_card: ^0.1.4
  cached_network_image: ^2.5.0
  ntp: ^1.0.8
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/master_card.png
    - images/visa.png



