name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.5.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  shared_preferences: ^2.0.7
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4
  firebase_storage: ^10.0.3
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.0
  path_provider: ^2.0.3
  image: ^3.0.4
  intl: ^0.17.0
  email_validator: ^2.0.1
  google_fonts: ^2.1.0
  page_transition: ^2.0.2
  google_maps_flutter: ^2.0.8
  geolocator: ^7.6.0
  geoflutterfire: ^3.0.1
  modal_progress_hud: ^0.1.3
  flutter_credit_card: ^3.0.1
  cached_network_image: ^3.1.0
  ntp: ^2.0.0
  firebase_messaging: ^10.0.7
  google_sign_in: ^5.1.0
  flutter_local_notifications: ^9.0.0
  flutter_signin_button: ^2.0.0
  curved_navigation_bar: ^1.0.1
  geocoding: ^2.0.1
  google_geocoding: ^0.2.0
  google_place: ^0.4.3
  awesome_card: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/master_card.png
    - images/visa.png



